spring:
  application:
    name: ddd
  datasource:
    url: jdbc:mysql://localhost:3306/ddd?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true